/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ContactUsRouteImport } from './routes/contactUs'
import { Route as AboutUsRouteImport } from './routes/aboutUs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as SolutionsSolutionIdRouteImport } from './routes/solutions.$solutionId'
import { Route as ResourcesResourcesIdRouteImport } from './routes/resources.$resourcesId'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contactUs',
  path: '/contactUs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/aboutUs',
  path: '/aboutUs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const SolutionsSolutionIdRoute = SolutionsSolutionIdRouteImport.update({
  id: '/$solutionId',
  path: '/$solutionId',
  getParentRoute: () => SolutionsRoute,
} as any)
const ResourcesResourcesIdRoute = ResourcesResourcesIdRouteImport.update({
  id: '/$resourcesId',
  path: '/$resourcesId',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contactUs': typeof ContactUsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/resources/$resourcesId': typeof ResourcesResourcesIdRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contactUs': typeof ContactUsRoute
  '/resources/$resourcesId': typeof ResourcesResourcesIdRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/resources': typeof ResourcesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutUs': typeof AboutUsRoute
  '/contactUs': typeof ContactUsRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/resources/$resourcesId': typeof ResourcesResourcesIdRoute
  '/solutions/$solutionId': typeof SolutionsSolutionIdRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutUs'
    | '/contactUs'
    | '/resources'
    | '/solutions'
    | '/resources/$resourcesId'
    | '/solutions/$solutionId'
    | '/resources/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutUs'
    | '/contactUs'
    | '/resources/$resourcesId'
    | '/solutions/$solutionId'
    | '/resources'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/aboutUs'
    | '/contactUs'
    | '/resources'
    | '/solutions'
    | '/resources/$resourcesId'
    | '/solutions/$solutionId'
    | '/resources/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactUs': {
      id: '/contactUs'
      path: '/contactUs'
      fullPath: '/contactUs'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutUs': {
      id: '/aboutUs'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/solutions/$solutionId': {
      id: '/solutions/$solutionId'
      path: '/$solutionId'
      fullPath: '/solutions/$solutionId'
      preLoaderRoute: typeof SolutionsSolutionIdRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/resources/$resourcesId': {
      id: '/resources/$resourcesId'
      path: '/$resourcesId'
      fullPath: '/resources/$resourcesId'
      preLoaderRoute: typeof ResourcesResourcesIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesResourcesIdRoute: typeof ResourcesResourcesIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesResourcesIdRoute: ResourcesResourcesIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSolutionIdRoute: typeof SolutionsSolutionIdRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSolutionIdRoute: SolutionsSolutionIdRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
